// Errors

func canThrowError() throws {
    
}

do {
    try canThrowError()
    // If error is not thrown
} catch {
    // If error is thrown
}